### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by tobiasdiez** [sagemath/conway-polynomials#1]
Needed for https://github.com/conda-forge/staged-recipes/pull/24585.

**Comment by orlitzky** [comment]
The project metadata has

```toml
license = { text = "GPL-3.0-or-later" }
```

Is that not sufficient? Adding a copy of the GPLv3 only risks confusion IMO since someone might misinterpret that as being GPLv3-only.

**Comment by orlitzky** [comment]
(I'm not dead set against it, I could also include a `COPYING` file that says "or later" and point the `pyproject.toml` at `COPYING`, but then it just seems like a lot of effort to repeat a standard SPDX license identifier.)

**Comment by tobiasdiez** [comment]
I don't have the legal background but my understanding is that the GNU licenses actually require you to distribute the exact full license text (eg https://opensource.stackexchange.com/questions/176/do-i-really-need-to-include-a-licence-file-for-common-licences-like-gpl-or-mit)

**Comment by orlitzky** [comment]
I guess Conda doesn't ship the usual licenses as part of the base install?

Upstream isn't bound by the GPLv3 yet, since we're the copyright holders and can do whatever we want. But distributions who redistribute the code are, so they would have to include a copy of the license. Debian and Gentoo get around it by shipping one copy of the license pointed to by the package metadata. But it looks like Fedora prefer the license file to be included, even though they still only install one copy to `/usr/share/licenses`.

I guess I'll just include them and not cause you headaches.

**Comment by tobiasdiez** [comment]
Thanks! If you could push a new version, then we should get https://github.com/conda-forge/staged-recipes/pull/24585 merged soon.

**Comment by orlitzky** [comment]
Done. I added some more examples and type hints to make a new version worthwhile. @mkoeppe will have to re-push the tag to get it on pypi.
